// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.0-c7d8c5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
